import React, { useEffect, useState } from 'react'
import Line from '../line'
import Right from '../right'
import Left from '../left'
import Top from '../top'
import H2 from '../h2'
const Spc = () => {
  const [Table, setTable] = useState([]);
  const fetchTable = async () => {
    try {
      const response = await fetch(`https://srgpc-colage.onrender.com/api/Table`);
      const data = await response.json();
  
      if (response.ok) {
        setTable(data); // Ensure we store an empty array if no data
      } else {
        alert("Error: " + data.message);
      }
    } catch (error) {
      console.error("Error fetching Table:", error);
    }
  };
  useEffect(() => {
      fetchTable();      
  },[]);
  useEffect(() => {
    Table.length > 0 ? (
      Table.map((t) => (
        document.getElementById("table").innerHTML+=t.table
      ))
    ) : (
      <p>No table found</p>
    )   
  },[Table]);
  return (
    <>
    <H2 h2={"Solar-Powered Campus"}/>
     <div id="carouselExampleControls" className="carousel slide" data-ride="carousel">
  <div className="carousel-inner">
    <div className="carousel-item active">
      <img className="d-block w-100 " src="/sc2.png" alt="First slide"/>
    </div>
    <div className="carousel-item">
      <img className="d-block w-100" src="/sc1.jfif" alt="Second slide"/>
    </div>
    <div className="carousel-item">
      <img className="d-block w-100" src="/sc3.jfif" alt="Third slide"/>
    </div>
  </div>
  <a className="carousel-control-prev" href="#carouselExampleControls" role="button" data-slide="prev">
    <span className="carousel-control-prev-icon" aria-hidden="true"></span>
    <span className="sr-only">Previous</span>
  </a>
  <a className="carousel-control-next" href="#carouselExampleControls" role="button" data-slide="next">
    <span className="carousel-control-next-icon" aria-hidden="true"></span>
    <span className="sr-only">Next</span>
  </a>
  </div>

  <H2 h2={"Electricity Bill Analysis of Main Building,"}/>
  <H2 h2={"After Solar Installation (IVRS-N1405010327)"}/>
  <div id="table" className ="main"></div>


        <div className="solar-container">
      <h2 >Off-Grid Solar System</h2>
      <p className="solar-description">
        Off-grid systems work independently of the grid but have batteries which
        can store the solar power generated by the system. The system usually
        consists of solar panels, battery, charge controller, grid box,
        inverter, mounting structure and balance of systems. The panels store
        enough sunlight during the day and use the excess power generated in the
        night. These systems are self-sustaining and can provide power for
        critical loads in areas where a power grid is not available. However,
        these systems require specialized equipment to function and can be
        costly to install. These are ideal for businesses which can sustain for
        a short period of time with no electricity.
      </p>
      <Line/>
      <h2 className="solar-subtitle">Applications:</h2>
      <ul className="solar-list">
        <li>
          <strong>Electricity supply in rural and remote areas -</strong> Off-grid
          solar systems can facilitate independent, long-term and sustainable
          electricity generation in rural and remote areas.
        </li>
        <li>
          <strong>Power backup in areas with frequent electricity cuts -</strong>
          A number of places in India face frequent power cuts due to power
          transmission malfunctions, which can hamper operations of companies
          and public institutions. Off-grid solar systems can provide an
          economical and viable long-term backup solution to overcome the
          problems occurring during frequent power cuts.
        </li>
      </ul>
      <Line/>
      <h2 className="solar-subtitle">Advantages:</h2>
      <ul className="solar-list">
        <li>These self-sustainable systems can work independently and do not rely on the grid.</li>
        <li>They generate enough power that can be stored and used at night or when the power grid is down.</li>
        <li>These are ideal for remote areas where there is no power access from the grid.</li>
        <li>Grid failures and shutdowns will not affect your power supply.</li>
      </ul>
      <Line/>
      <h2 className="solar-subtitle">UTL Solar Panel:</h2>
      <p className="solar-description">
        UTL solar panels are the latest technology and most innovative solar
        panels. A solar photovoltaic panel is a composition of solar
        photovoltaic cells, well arranged together in an aluminium frame and
        covered with high-quality glass.
      </p>
      <Line/>
      <h2 className="solar-subtitle">Installation Guidelines:</h2>
      <p className="solar-description">
        The installation of Solar Power System involves the following major steps:
      </p>
      <ul className="solar-list">
        <li>Civil Foundation Job</li>
        <li>Assembly and fixing of support structure.</li>
        <li>Mounting of Solar Modules on the Support Structure.</li>
        <li>Installation of Battery Bank.</li>
        <li>Interconnection of SPV panel in series & parallel configuration, Charge Control Unit and FJB</li>
        <li>Connection of Battery Bank and Load</li>
        <li>Earthing of Lightning Protection Unit.</li>
      </ul>
    </div>
    </>
  )
}

export default Spc
